name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "assets/snake.svg"

concurrency:
  group: snake
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: rasuliyonn
          outputs: |
            dist/snake.svg?color_snake=#818CF8&color_dots=#0B1120,#1E293B,#334155,#818CF8,#38BDF8

      - name: Move into assets
        run: |
          mkdir -p assets
          mv dist/snake.svg assets/snake.svg

      - name: Commit snake
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: обновить snake-график"
          file_pattern: assets/snake.svg
